### ISSUE TITLE
Windows host support

### ISSUE THREAD

**Issue by JoshuaWierenga** [jart/blink#16]
Are there any plans for getting blink to run on windows hosts? Mostly interested in this so cosmopolitan applications can run on 32 bit windows nt. If possible, it might also be worth adding x86_32 support to ape again to create a fat binary and adding that to blink so that there aren't multiple blink binaries for one os.

**Comment by jart** [comment]
The most recent Blinkenlights release will run great on Windows x64. https://justine.lol/blinkenlights/download.html There's obviously been a lot of great work on Blinkenlights in this repository since then. The plan is to have Blink be able to be compiled using Cosmopolitan Libc's `cosmocc` toolchain. That way our new POSIX-only code will *just work* on Windows x64. There's nearly zero chance Blink will be changed to compile under something MSVC, so unfortunately Windows 32-bit support is unlikely.

**Comment by lokman2k5** [comment]
is there any up-to-date version? this one is from 2022
