### ISSUE TITLE
A number of minor issues

### ISSUE THREAD

**Issue by tkchia** [jart/blink#2]
Hello @jart,

I encountered a few issues while trying to build and run `blink` (https://github.com/jart/blink/commit/1d13bfd50c16c9b5c16892465d5d91f7984007e2):

* `README.md` says to run `make -j8 o///blink/blink`, but this does not work.  Should this be `make -j8 o//blink/blink` (with two slashes)?
* Running `make -j8 o//blink/tui` gives a warning message.  The build succeeds however.
  ```
  blink/tui.c: In function ‘SetStatus’:
  blink/tui.c:2203:3: warning: ignoring return value of ‘vasprintf’ declared with attribute ‘warn_unused_result’
   [-Wunused-result]
   2203 |   vasprintf(&s, fmt, va);
        |   ^~~~~~~~~~~~~~~~~~~~~~
  ```
* The `tui` help screen formatting seems a bit broken, for some reason.  If I run `o//blink/tui -t third_party/cosmo/hello.com` under X Window `xterm` (`-geometry 200x50 -title xterm -e sh`), then press the `?` command key, I get the following:
  ![20221104-1](https://user-images.githubusercontent.com/5507843/200066567-06565276-d84c-4bd9-9709-9505253be0b2.png)
* And, I think it will be good if the `?` command key can be documented in the `USAGE` message, not just in the help screen itself.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> The tui help screen formatting seems a bit broken, for some reason.

I have a PR fix for that coming shortly. The reason has to do with the added CRs in the HELP message in tui.c. I hope to have a couple other small display issues fixed in that as well.

Thank you!

**Comment by ghaerr** [comment]
The other enhancement I'm working on is providing the ability to display the Terminal/Teletypewriter output column (which could also be the MDA or CGA output) when the window is less than 240 characters wide. This is because on macOS, one can't display windows wider than 240 characters without reducing the font width. In the revised version, the Teletype/MDA/CGA panel would be truncated on the right hand side, rather than missing entirely.

**Comment by jart** [comment]
Now that #3 is merged, are we OK to close this one out?

**Comment by tkchia** [comment]
@jart: OK.  Thank you!
