### ISSUE TITLE
Questions, regarding blink:

### ISSUE THREAD

**Issue by FrostKnight** [jart/blink#52]
How functional is this compared to qemu on different architectures and different operating systems?

interested in unix based ones like OpenBSD and a few others, including Hyperbola.

Mostly interested because wondering if this would work well with ARM64, regarding running x86 or x86_64 on OpenBSD, etc...

Looks like an interesting project btw.

**Comment by jart** [comment]
Blink does a pretty good job running Linux binaries on other operating systems. As far as I know, Blink is the only project that can do this without emulating the Linux kernel too. qemu-x86_64 only supports Linux. Please see however the caveats described in the README.

I regularly test this project works great on OpenBSD and FreeBSD. OpenBSD required some cleverness to support, due to its W^X invariant. We're still able to offer JIT on OpenBSD despite that. Our NetBSD support isn't fully tested yet, but SDF is in the process of helping me get set up with a shell account soon so I can do that. As for Hyperbola, I haven't heard of it. If it's POSIX then it should work.

As for other architectures, I regularly test this project on Apple M1 and Raspberry Pi. Our ARM support is JITed and very good. I also regularly test this project on 11 hardware architectures total, with the assistance of Qemu. Even big endian ones, like s390x. However those architectures aren't JITed yet. Contributions welcome.

**Comment by FrostKnight** [comment]
Would this:
https://shop.mntre.com/products/mnt-reform
or this below:
https://mntre.com/media/reform_md/2022-06-20-introducing-mnt-pocket-reform.html
work moderately well with blink?
Like 30+ FPS, or whatever measurement you would use,  that is relevant, etc...
OpenBSD supposedly works on those devices, even if not officially supported yet, as far as I know? Idk.
The setups currently they have are these:
Imx8m Quad 4GB RAM or Imx8m Plus 8GB RAM or LS1028A 8GB RAM 

I wondered how well each would work regarding blink and as an obvious, yes it would have OpenBSD on them.

**Comment by jart** [comment]
Blink should work great on your OpenBSD ARM64 laptop. If this is a platform you depend on then what I recommend doing is donating one of those laptops to the project, and I'll use it in the test fleet.
